{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress-healthz.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ingress-healthz.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
{{- if .host }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
{{- else }}
    - {}
{{- end }}
{{- if .secretName }}
      secretName: {{ .secretName }}
{{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
{{- if .host }}
    - host: {{ .host | quote }}
      http:
{{- else }}
    - http:
{{- end }}
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- end }}
    {{- end }}
  {{- end }}
